name: Docker Build and Push

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-build.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: freemankevin/nacos-mysql:v8
          platforms: linux/amd64,linux/arm64
          build-args: |
            MYSQL_VERSION=8.3.0

      # Trivy vulnerability scan
      - name: Scan the Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'freemankevin/nacos-mysql:v8'
          format: 'table'
          exit-code: '0' # Even if vulnerabilities are found, do not fail the step
          ignore-unfixed: true
          vuln-type: 'os,library'


      # Clair vulnerability scan
      - name: Scan the Docker image with Clair
        env:
          IMAGE_NAME: freemankevin/nacos-mysql
          IMAGE_TAG: v8
        run: |
          # Start Clair scanner
          docker run -d --name clair-scanner -p 6060:6060 arminc/clair-scanner:latest
          
          # Wait for Clair scanner to start
          sleep 10
          
          # Scan your Docker image with Clair
          docker pull $IMAGE_NAME:$IMAGE_TAG
          CLAIR_ADDR=http://localhost:6060 clair-scanner --ip "$(hostname -i)" -t High --report /tmp/clair-report.json $IMAGE_NAME:$IMAGE_TAG
          
          # Show the Clair scan report
          cat /tmp/clair-report.json
          
      - name: Logout from DockerHub
        if: always()
        run: docker logout